micronaut:
  application:
    name: helloApp
  server:
    port: 8084
r2dbc:
  datasources:
    default:
      url: r2dbc:postgresql://localhost:5432/hello
      username: cogoport
      password: cogoport123
      dialect: POSTGRES
netty:
  default:
    allocator:
      max-order: 3
